project:
  type: website

website:
  title: "Ahmad Ghalawinji Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo